def part1(string)
  string.chars.reduce(0) do |acc, char|
    case char
    when 'A'
      acc
    when 'B'
      acc + 1
    when 'C'
      acc + 3
    else
      acc
    end
  end
end

puts "Part 1"
puts part1('ABBAC')
puts part1('CCBCCCAACCACCACCABABBAACCBCCCABBCAABACAAAAACBCACAACCAACACBCACCCCBBAAAAACCCCABAACBACAABCCCBBACBACBBABCBCBCBABABCCBCBABCAACBABAACBCBABBCABBCAACBBCCABBAAABACBCBBCACAABBACAAABAAACCABACCACCCAACCAACACCACCBABACBBBAAAABCACABCACABCCBAABCCAABAABCABABACCBBABCACAACABCBBCABBBBCBBAABCCBACAACABCBBAACACABCCBCBCCCACABBAAABBCAACCCCABBAACABAAACBCAACAABAAABBCAAACAACABBCCCABCACCAACBABCCCCBBBABBBAACAAACBCAACCCABBAACABBAABCACCBBCABCACCACCBACABACBBACBABBCCCCBAACAACACABBACAAACCACBCBBCABBBCAACBBBBCCAABABBCBABACBABBABBAACBBBAABCAABABBABABABAACBCACABBCBBCAACBCAAABACCAACAAAABCAABCBCBBBBACACBACABBACACCCAACCBACBABABCAAAAACACCBCABACACCBABCACBBABBBCBBCCCAAABBAAACACACBBAABABAABABAABBABAABBCCAABBABCCCCBBCABCCACAABAABACBCACBABCAABCACBBCCBBCBCAACAAAAACCAACACBBCBCABBCBCBBCBBCCAABAACABCACABAAACBAACCACBAAABBACBBBACBCCCCABACCCCCCBCBBAAAACCBAACCCBCACCAABBCCACCBCABBACCBAABCACCBBCABBCACACBCCABBACCCCCABAAABCCABABBBBCBAAABACCCABCBBABCACAABBACCAABCBAAAACABABAAAABBBCCCBACCCAAABABBABBBABBACBCACBBBBCCABAAACCBBBBCCCCCCBBCBABBABCAACCBBA')

def part2(string)
  (0..string.size / 2).reduce(0) do |acc, i|
    case string[i * 2, 2]
    when 'A', 'Ax', 'xA'
      acc
    when 'B', 'Bx', 'xB'
      acc + 1
    when 'AA'
      acc + 2
    when 'C', 'xC', 'Cx', 'AB', 'BA'
      acc + 3
    when 'BB'
      acc + 4
    when 'D', 'Dx', 'xD', 'AC', 'CA'
      acc + 5
    when 'BC', 'CB'
      acc + 6
    when 'AD', 'DA'
      acc + 7
    when 'CC', 'BD', 'DB'
      acc + 8
    when 'CD', 'DC'
      acc + 10
    when 'DD'
      acc + 12
    else
      acc
    end
  end
end

puts "Part 2"
puts part2('AxBCDDCAxD')
puts part2('AADDCxBACBBxAADCxCCDAxAABACxBCBADDBDDDBxACACBCBBBACCBDDABBxxDCCDCAABAACxxDDDDDBCADxDDDDCBxBCDADACDAxAxBDxxCxAACBCBDBDBAABCABBCCCBCCCCxABDBCCxDABACDxCCADxCCDDBCBCCABCDBBCACAxCDDDCCABABCxDDBCxBDDDAxDDDCDxBCDBDDBCBCBCDDBxBBACBBBACxADDABBBDBxCxABBBDBDACCxACxDADDDBCACBDxADABABAxCCAxDAABDDABDCABDCACCBBACxBBCDCBCBBAAADCBAADBxBBxxCACABBADDCCACDCACDACCCBACBCADCBxCxBDBxBCADBDACAAADAACCACBCCCBxDACxxAABBCCBAxCACCCABCBCBCDBxABABACABBxCBCDDCACACAxAABDBCDDBBCABDBADBADCxCDAABCCABDACBCCxCDDBAAADADADCCCAADBCADADBCBBDDAxADBCDCCBDDCBxAAxAACCCxxBABBBxxCxDBDDBBDDDBxxBAABABDBDAABxBADDAADCxBxAAABxBDBBADxAxDDDCACDBAAABBDDCDDCACxCDxCAABBDBBBDAADDACAAABCCBBCDDCAABAABCCAADAxBxAxBCABBDBDxDBADACBxCDDADABBACDDAxCBBDAxDAxDxxABDCCDBBADDACCBCDxDAABBDAxDCCCDxADBCBxABxCBBBBACCAxCAAxCACDBABBCACCxCACCDDBBCBBBDDDBDADBAxDBCCADDDDDAADBBCDCCDDCDCAAADCBBxDxBADABBABBCxDDABxAxCBBDBBCDxBBxCDBBxAxDDCABADDxDDDxAAAABADBCAxBBAABBCxACCABAAAxxBDCBBAxCCBCBBABCBADBABBAADCCDCAxAADBxCBDCABxDBAxABABDADDDxBxACBCDDDBBBDDBDADCDBBBBBACBCACABCxABCADCDCAABABACAABDBDAAADDDAxBDDCACBBDDBABBCDCABDDABACxCAABxDBDDADBBDAACBBxAABADBBBDBDCDABxACCDDCxADBxxDCDBAACDBDDCBBBxDCACxBDBDCxCDBDACBCDCBxAxBxAABBCBxCBAAxAADDDCBADDCxCDACAADDAxDAxDBCADBBDBCCBCCBBDAxDAxBDABDCCAxCCAADACBACBAABADBCCCACCACBCCACBDBCBBxADDBCABCDACDCDCBDxBAABCDBCCCCBADDDDxBxBAxBBDDBBBDCBCBDBCBAADBxBDBCADCCxBDBDDCxDAADCAAADCCBABDDBBCDBBABxBDABxxAACACBBAAACxBCxDAAxACCDCABBBCCABxCCBBDDDDxDBADxCACABCDxAACCADDDBCxDCCDBCBxDDAxDxxDBDBBDBBDCADBBDBDACAADDBDACDABCCBAACABBCBDBBCDADACADDBDDADBAxBBCCxDBDDCBDxACCABCAxCAAABBCCADCADCBAxACBADACBBBCBAAxCAABDAADBBBBxCCxDACDDBCACxDDABCDAxDABCxCAxxBABDBCBBBABxDBDDDBBDCADCDxxAAABBxABBCBxxCBCDDxxBCADACACCBCDxAADBCAABADADBBCBxADAxxAACAACACBBADDACCAxABCBAAABxDBxDBCCBCAAxDADCCDxBCAADDCBCBACxDBBAACDDBBCBCxBDBBCAABDBADDADABDDCDBCDBCBDDDCCBADBxDACBBxDBBBDADCDDCDABxDBDBBBADBABDBAxxBAABCCAxBDCDDBCABDxxDDBADBDDDAxAxCABBCBxBAADDAAACBDBCxAACxDDBABCABACBDCxADBACxCDCCCACxDDDBAACACCCxACACDCABCCDBDABDxxAACCAAxAxABBBxAAACABABCDDDAABxDCxBAxCDBBxADDBCBCCBBDBBCAACA')
